/**
 * Second deck: opposition & parliament, deeper institutional loops, more economy and society.
 */
import type { Card } from './cards';
import type { BlocId } from './types';

const all = (blocs: Partial<Record<BlocId, number>>) => blocs;

export const EXTRA_CARDS: Card[] = [
  // ------------------------------------------------------------------ opposition & parliament
  {
    id: 'opp-leader',
    title: 'The opposition has a new leader',
    category: 'politics',
    learn: ['opposition'],
    body: 'After months of infighting the opposition has chosen a fresh face. The honeymoon polls are ugly for you.',
    condition: (s) => s.opposition.leaderTurns < 2 && s.turn > 2,
    weight: 3,
    cooldown: 8,
    options: [
      { label: 'Attack their record', description: 'Define them before they define themselves. Works better if trust is high.', effects: { fn: (s) => { s.opposition.credibility -= s.trust > 45 ? 6 : 1; s.trust -= 1; } } },
      { label: 'Ignore them, govern', description: 'Rise above it.', effects: { stocks: { trust: 1 } } },
      { label: 'Steal their best policy', description: 'Shift toward their platform. Your party grumbles; their pitch weakens.', effects: { stocks: { partyUnity: -4 }, opposition: { credibility: -3 }, blocs: all({ working: 2, pensioners: 2 }) } },
    ],
  },
  {
    id: 'populist-split',
    title: 'A populist insurgency',
    category: 'politics',
    learn: ['opposition', 'integration'],
    body: 'A new party is surging on migration and "the establishment". It is taking voters from you and from the opposition, and shifting the whole debate.',
    condition: (s) => s.cohesion < 50 || s.trust < 33,
    weight: 2,
    cooldown: 12,
    options: [
      { label: 'Co-opt the agenda', description: 'Tighter migration, tougher rhetoric. Your liberal wing despairs.', effects: { levers: { migrationOpenness: -10 }, stocks: { cohesion: -2, partyUnity: -3 }, opposition: { credibility: -4, platform: { migration: -0.2 } }, blocs: all({ working: 4, pensioners: 4, young: -5, middle: -3, business: -2 }) } },
      { label: 'Confront it', description: 'Make the case for an open, orderly country. Risky if cohesion is already low.', effects: { stocks: { trust: 2 }, opposition: { credibility: 2 }, blocs: all({ young: 4, middle: 2, working: -3, pensioners: -3 }) } },
      { label: 'Let it split the opposition', description: 'Say nothing and enjoy the chaos on the other side.', effects: { opposition: { credibility: -6, platform: { migration: -0.3, authority: 0.2 } }, stocks: { cohesion: -3 } } },
    ],
  },
  {
    id: 'by-election',
    title: 'By-election drubbing',
    category: 'politics',
    learn: ['voter-blocs'],
    body: 'You have lost a safe seat on a 20-point swing. The papers call it a verdict on your government.',
    condition: (s) => s.nationalApproval < 42,
    weight: 2,
    cooldown: 8,
    options: [
      { label: '"We are listening"', description: 'Promise a reset. A modest trust gain if you then actually change something. One seat fewer either way.', effects: { stocks: { trust: 1, partyUnity: -3 }, fn: (s) => { s.majority -= 2; } } },
      { label: 'Blame local factors', description: 'Nobody believes you. One seat fewer either way.', effects: { stocks: { trust: -2, partyUnity: -5 }, opposition: { credibility: 3 }, fn: (s) => { s.majority -= 2; } } },
    ],
  },
  {
    id: 'defection',
    title: 'An MP crosses the floor',
    category: 'politics',
    learn: ['opposition'],
    body: 'A backbencher has defected to the opposition live on television, citing "a government that has lost its way".',
    condition: (s) => s.partyUnity < 45 && s.opposition.national > 36,
    weight: 2,
    cooldown: 10,
    options: [
      { label: 'Wish them well', description: 'Dignified. Your majority falls by two.', effects: { stocks: { partyUnity: -3, trust: 1 }, opposition: { credibility: 2 }, fn: (s) => { s.majority -= 2; } } },
      { label: 'Brief against them', description: 'Dirt in the Sunday papers. The party enjoys it; the public does not. Your majority falls by two.', effects: { stocks: { partyUnity: 2, trust: -2, pressFreedom: -1 }, opposition: { credibility: 1 }, fn: (s) => { s.majority -= 2; } } },
    ],
  },
  {
    id: 'fiscal-rule-broken',
    title: 'The OBR says you have broken your rule',
    category: 'economy',
    learn: ['fiscal-rules'],
    body: "The Office for Budget Responsibility's forecast shows the government in breach of its own fiscal rule. The Chancellor must respond at the Budget.",
    condition: (s) => s.fiscalRule !== 'none' && s.ruleHeadroom < 0 && s.year >= 2029 && s.quarter === 1,
    weight: 2,
    cooldown: 12,
    options: [
      { label: 'Spending restraint', description: 'Trim welfare and capital budgets. Markets satisfied; the left of the party is not.', effects: { levers: { welfare: -0.3, infrastructure: -0.2 }, stocks: { riskPremium: -0.3, trust: -1, unrest: 2 }, blocs: all({ business: 3, working: -2, publicSector: -2, young: -1 }) } },
      { label: 'Raise taxes', description: 'A penny on income tax. Markets satisfied; the middle is not.', effects: { levers: { incomeTax: 1 }, stocks: { riskPremium: -0.3, trust: -1 }, blocs: all({ business: 3, middle: -2, working: -2 }) } },
      { label: 'Rewrite the rule', description: 'Move the goalposts. Credibility falls, and the next breach costs more.', effects: { stocks: { riskPremium: 0.4, trust: -3, businessConfidence: -4 }, blocs: all({ business: -5, middle: -2 }), fn: (s) => { s.ruleBreaches += 4; } } },
      { label: 'Blame the forecast', description: "Dispute the OBR's numbers. Nothing changes, and the institution is dented.", effects: { stocks: { trust: -2, judicialIndependence: -1, riskPremium: 0.2 }, blocs: all({ business: -3 }) } },
    ],
  },
  {
    id: 'confidence-motion',
    title: 'Motion of no confidence',
    category: 'crisis',
    learn: ['parliament'],
    body: 'With your majority gone, the opposition has tabled a motion of no confidence. Losing it means an early election you are unlikely to win.',
    condition: (s) => s.majority <= 4,
    weight: 6,
    cooldown: 6,
    options: [
      { label: 'Do a deal with a smaller party', description: 'Buy their votes with policy: devolution, welfare, green money.', effects: { levers: { welfare: 0.2, green: 0.2 }, stocks: { partyUnity: -4, trust: -1 }, fn: (s) => { s.majority = Math.max(s.majority, 6); } } },
      { label: 'Face the vote', description: 'Survive if your party is united; otherwise the government falls.', effects: { fn: (s) => { if (s.partyUnity + s.majority > 52) { s.majority = Math.max(s.majority, 5); s.partyUnity += 6; s.honeymoon += 2; } else { s.partyUnity = 0; } } } },
    ],
  },
  // ------------------------------------------------------------------ institutions, deeper
  {
    id: 'bbc-charter',
    title: 'BBC charter renewal',
    category: 'institutions',
    learn: ['institutions'],
    body: 'The licence fee is up for renewal. Your press allies want the corporation cut down; the public trusts it more than it trusts you.',
    condition: (s) => s.turn > 6,
    cooldown: 40,
    options: [
      { label: 'Renew with independence guarantees', description: 'Boring, institutionally sound.', effects: { stocks: { pressFreedom: 3, trust: 1 }, blocs: all({ middle: 2, pensioners: 1, business: -1 }) } },
      { label: 'Cut the fee, appoint the chair', description: 'Cheaper telly, friendlier coverage, weaker scrutiny.', effects: { stocks: { pressFreedom: -8, corruption: 3 }, blocs: all({ working: 2, business: 2, middle: -3, young: -2 }) } },
    ],
  },
  {
    id: 'whistleblower',
    title: 'Whistleblower',
    category: 'institutions',
    learn: ['corruption'],
    body: 'A civil servant has leaked documents showing ministers ignored official advice on a procurement deal. The case hinges on whether the courts protect the leaker.',
    condition: (s) => s.corruption > 28,
    weight: 2,
    cooldown: 10,
    options: [
      { label: 'Protect the whistleblower, publish the advice', description: 'Painful, cleansing.', effects: { stocks: { corruption: -8, trust: -2, judicialIndependence: 2, pressFreedom: 2 }, blocs: all({ middle: 2, working: -1 }) } },
      { label: 'Prosecute under the Official Secrets Act', description: 'Chilling effect. Corruption keeps growing in the dark.', effects: { stocks: { pressFreedom: -6, judicialIndependence: -3, corruption: 4, trust: -3 }, blocs: all({ middle: -3, young: -3 }) } },
    ],
  },
  {
    id: 'emergency-powers',
    title: 'Emergency powers',
    category: 'institutions',
    learn: ['institutions', 'unrest'],
    body: 'With unrest high, the Home Secretary proposes emergency powers: protest bans, detention without charge, and a suspension of judicial review "for the duration".',
    condition: (s) => s.unrest > 60,
    weight: 3,
    cooldown: 8,
    options: [
      { label: 'Take the powers', description: 'Unrest drops fast. Institutions, cohesion and standing take lasting damage.', effects: { stocks: { unrest: -20, judicialIndependence: -12, pressFreedom: -8, cohesion: -5, internationalStanding: -8, businessConfidence: -5 }, blocs: all({ pensioners: 4, working: 1, young: -8, middle: -5 }) } },
      { label: 'Police within the law', description: 'Slower, and it holds the line on the rule of law.', effects: { stocks: { unrest: -6, judicialIndependence: 1 }, levers: { policing: 0.2 }, blocs: all({ middle: 2, young: 1, pensioners: -2 }) } },
      { label: 'Negotiate with the protest leaders', description: 'Concessions and a public inquiry.', effects: { stocks: { unrest: -10, trust: 2, partyUnity: -4 }, levers: { welfare: 0.2 }, blocs: all({ young: 3, working: 2, business: -3, pensioners: -3 }) } },
    ],
  },
  {
    id: 'electoral-commission',
    title: 'Rigging the rules?',
    category: 'institutions',
    learn: ['institutions', 'elections'],
    body: "A bill would let ministers set the Electoral Commission's priorities and tighten voter ID. Your whips say it is worth two points at the next election.",
    condition: (s) => s.turn > 4,
    cooldown: 30,
    options: [
      { label: 'Pass it', description: 'A small structural edge, a large cost to trust and standing.', effects: { flags: { campaignBonus: 1.5 }, stocks: { trust: -4, judicialIndependence: -4, internationalStanding: -4 }, blocs: all({ young: -4, middle: -3 }) } },
      { label: 'Drop it', description: 'Play fair.', effects: { stocks: { trust: 1 }, blocs: all({ middle: 1, young: 1 }) } },
    ],
  },
  {
    id: 'governor-appointment',
    title: 'A new Governor for the Bank',
    category: 'institutions',
    learn: ['taylor-rule', 'inflation-expectations'],
    body: "The Governor's term is ending. You can appoint a respected central banker or a political ally who \"understands growth\".",
    condition: (s) => s.turn > 8,
    cooldown: 32,
    options: [
      { label: 'The respected technocrat', description: 'Markets nod approvingly.', effects: { stocks: { cbIndependence: 5, riskPremium: -0.2 }, blocs: all({ business: 3 }) } },
      { label: 'The political ally', description: 'Lower rates than the rule implies. Expectations drift.', effects: { stocks: { cbIndependence: -20, inflationExpectations: 0.5, sterling: -3 }, blocs: all({ working: 2, young: 2, business: -4 }) } },
    ],
  },
  // ------------------------------------------------------------------ economy, more
  {
    id: 'sterling-crisis',
    title: 'Run on the pound',
    category: 'crisis',
    learn: ['sterling', 'risk-premium'],
    body: 'Sterling has fallen 10% in a fortnight. Import prices are jumping and the Bank is talking about an emergency rate rise.',
    condition: (s) => s.sterling < 85,
    weight: 4,
    cooldown: 8,
    options: [
      { label: 'Back an emergency rate rise', description: 'Stabilises the currency, hits growth and mortgages.', effects: { fn: (s) => { s.bankRate += 1.5; s.sterling += 6; s.outputGap -= 0.5; }, blocs: all({ business: 2, working: -3, young: -3 }) } },
      { label: 'Fiscal tightening to reassure markets', description: 'Cut spending; premium falls.', effects: { levers: { infrastructure: -0.3, welfare: -0.3 }, stocks: { riskPremium: -0.5, sterling: 4, unrest: 4 }, blocs: all({ business: 3, working: -4, publicSector: -3 }) } },
      { label: 'Let it float', description: 'Cheaper exports, dearer imports. Inflation follows.', effects: { stocks: { inflationExpectations: 0.5, outputGap: 0.3 }, blocs: all({ pensioners: -2 }) } },
    ],
  },
  {
    id: 'minimum-wage',
    title: 'Living wage review',
    category: 'economy',
    learn: ['okun', 'inequality'],
    body: 'The Low Pay Commission is split. Unions want a big rise; small businesses say it will cost jobs.',
    condition: (s) => s.turn > 3,
    cooldown: 16,
    options: [
      { label: 'Big rise', description: 'Inequality down; a little structural unemployment and inflation up.', effects: { stocks: { gini: -0.008, inflation: 0.3, businessConfidence: -3 }, fn: (s) => { s.nairu += 0.2; }, blocs: all({ working: 5, young: 3, publicSector: 2, business: -5 }) } },
      { label: 'Inflation-linked rise', description: 'Steady as she goes.', effects: { blocs: all({ working: 1, business: 1 }) } },
      { label: 'Freeze it', description: 'Business cheers; low-paid workers seethe.', effects: { stocks: { gini: 0.005, businessConfidence: 2 }, blocs: all({ business: 4, working: -5, young: -3 }) } },
    ],
  },
  {
    id: 'water-companies',
    title: 'Sewage in the rivers',
    category: 'environment',
    learn: ['institutions'],
    body: 'Privatised water companies have paid out billions in dividends while pumping sewage into rivers. One is about to go bust.',
    condition: (s) => s.turn > 2,
    cooldown: 24,
    options: [
      { label: 'Nationalise the failing company', description: 'Popular, costs money, signals to investors.', effects: { stocks: { debt: 20, businessConfidence: -4, trust: 2, emissions: -2 }, blocs: all({ working: 3, young: 4, middle: 2, business: -5 }) } },
      { label: 'Fines and a tougher regulator', description: 'Institutional fix. Slower.', effects: { stocks: { judicialIndependence: 1, trust: 1, emissions: -1 }, blocs: all({ middle: 2, business: -1 }) } },
      { label: 'Let it go bust, protect customers', description: 'Market discipline with a safety net.', effects: { stocks: { debt: 8, businessConfidence: 1 }, blocs: all({ business: 2, working: -2 }) } },
    ],
  },
  {
    id: 'nato-spending',
    title: 'Allies demand 3% on defence',
    category: 'economy',
    learn: ['fiscal-multiplier'],
    body: "With a war on Europe's border, allies want the UK at 3% of GDP on defence. The money has to come from somewhere.",
    condition: (s) => s.levers.defence < 3 && s.turn > 4,
    cooldown: 20,
    options: [
      { label: 'Commit to 3% by borrowing', description: 'Standing up, deficit up.', effects: { levers: { defence: 0.5 }, stocks: { internationalStanding: 6 }, blocs: all({ pensioners: 3, business: 1, young: -2 }) } },
      { label: 'Commit to 3% by cutting welfare', description: 'Fiscally neutral, socially costly.', effects: { levers: { defence: 0.5, welfare: -0.5 }, stocks: { internationalStanding: 3, unrest: 3 }, blocs: all({ pensioners: 2, working: -3, young: -3 }) } },
      { label: 'Decline', description: 'Standing falls; allies grumble.', effects: { stocks: { internationalStanding: -6 }, blocs: all({ pensioners: -3, young: 1 }) } },
    ],
  },
  {
    id: 'teacher-shortage',
    title: 'Teacher shortage',
    category: 'society',
    learn: ['human-capital'],
    body: 'A third of new teachers leave within five years. Class sizes are rising and maths posts are unfillable.',
    condition: (s) => s.educationQuality < 47,
    weight: 2,
    cooldown: 10,
    options: [
      { label: 'Pay and workload deal', description: 'Costs money, works.', effects: { levers: { education: 0.3 }, stocks: { educationQuality: 2 }, blocs: all({ publicSector: 5, young: 2, middle: 2 }) } },
      { label: 'Fast-track unqualified teachers', description: 'Fills the gap; quality suffers.', effects: { stocks: { educationQuality: -2, humanCapital: -0.3 }, blocs: all({ publicSector: -4, middle: -2, business: 1 }) } },
    ],
  },
  {
    id: 'universities',
    title: 'Universities on the brink',
    category: 'society',
    learn: ['human-capital', 'migration'],
    body: 'Falling foreign student numbers have left several universities insolvent. Whole towns depend on them.',
    condition: (s) => s.levers.migrationOpenness < 40,
    weight: 2,
    cooldown: 16,
    options: [
      { label: 'Exempt students from the migration cap', description: 'Universities saved; migration numbers rise.', effects: { stocks: { netMigration: 60, humanCapital: 0.4, businessConfidence: 2 }, blocs: all({ middle: 2, young: 3, business: 2, working: -2, pensioners: -3 }) } },
      { label: 'Bail them out', description: 'Costs money; the problem returns.', effects: { stocks: { debt: 6 }, blocs: all({ publicSector: 2, middle: 1 }) } },
      { label: 'Let them merge or close', description: 'Skills and regional economies suffer.', effects: { stocks: { humanCapital: -0.6, outputGap: -0.2 }, blocs: all({ young: -4, middle: -3, publicSector: -3, working: -1 }) } },
    ],
  },
  {
    id: 'four-day-week',
    title: 'The four-day week',
    category: 'society',
    learn: ['happiness', 'productivity'],
    body: 'Trials show a four-day week raises wellbeing with little productivity loss. Unions want it in the public sector; business calls it madness.',
    condition: (s) => s.year >= 2029,
    cooldown: 30,
    options: [
      { label: 'Public sector pilot', description: 'Happier staff, slightly higher cost.', effects: { levers: { nhs: 0.1, education: 0.1 }, stocks: { happiness: 2 }, blocs: all({ publicSector: 6, young: 3, business: -3 }) } },
      { label: 'Not now', description: 'Nothing changes.', effects: { blocs: all({ business: 2, publicSector: -2 }) } },
    ],
  },
  {
    id: 'devolution',
    title: 'The union under strain',
    category: 'politics',
    learn: ['integration'],
    body: 'Scotland wants another independence referendum and the English regions want the powers London keeps promising.',
    condition: (s) => s.turn > 6 && s.trust < 45,
    cooldown: 30,
    options: [
      { label: 'Big devolution settlement', description: 'Power and money out of Whitehall. Cohesion and trust up over time.', effects: { stocks: { trust: 3, cohesion: 3, partyUnity: -3 }, blocs: all({ middle: 2, young: 2, working: 1 }) } },
      { label: 'Refuse a referendum, hold the line', description: 'Short-term stability, resentment grows.', effects: { stocks: { cohesion: -3, trust: -1 }, blocs: all({ pensioners: 2, young: -2 }) } },
    ],
  },
];
